
recorder:
  rate: 16384           # Sampling rate in Hz

spectrogram:
  duration: 60          # Duration of the spectrogram in seconds
  window_size : 2048    # Window size for fft
  window_overlap: 1536  # Window overlapping
